"""Deterministic OpenAPI and TypeScript contract export for Jarvis Agent."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from fastapi import FastAPI

from openjarvis.server.jarvis_agent.api.router import router as agent_router
from openjarvis.server.jarvis_agent.edge.router import router as edge_router

_TS_HEADER = """// Generated by scripts/workspace/export-jarvis-agent-contracts.py.
// Do not edit manually; update the backend Pydantic contracts and regenerate.

"""


def build_openapi() -> dict[str, Any]:
    app = FastAPI(title="OpenJarvis Jarvis Agent API", version="2.0.0")
    app.include_router(agent_router)
    app.include_router(edge_router)
    return app.openapi()


def _property_name(name: str) -> str:
    return name if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) else json.dumps(name)


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)


def _type_expression(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(item) for item in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(_type_expression(item) for item in schema["anyOf"])
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_type_expression({"type": item}) for item in schema_type)
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        prefix = schema.get("prefixItems")
        if isinstance(prefix, list):
            return "[" + ", ".join(_type_expression(item) for item in prefix) + "]"
        item_type = _type_expression(schema.get("items") or {})
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        fields = [
            f"{_property_name(name)}{' ' if name in required else '?'}: "
            f"{_type_expression(value)}"
            for name, value in properties.items()
        ]
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            fields.append(f"[key: string]: {_type_expression(additional)}")
        elif additional is True:
            fields.append("[key: string]: unknown")
        return "{ " + "; ".join(fields) + " }"
    if isinstance(schema.get("additionalProperties"), dict):
        return f"Record<string, {_type_expression(schema['additionalProperties'])}>"
    return "unknown"


def render_typescript(openapi: dict[str, Any]) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    blocks = [_TS_HEADER.rstrip()]
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") == "object" and "properties" in schema:
            required = set(schema.get("required") or [])
            lines = [f"export interface {name} {{"]
            for field, value in schema["properties"].items():
                marker = "" if field in required else "?"
                lines.append(
                    f"  {_property_name(field)}{marker}: {_type_expression(value)};"
                )
            lines.append("}")
            blocks.append("\n".join(lines))
        else:
            blocks.append(f"export type {name} = {_type_expression(schema)};")
    return "\n\n".join(blocks) + "\n"


def contract_contents() -> tuple[str, str]:
    openapi = build_openapi()
    openapi_text = (
        json.dumps(openapi, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )
    return openapi_text, render_typescript(openapi)


def write_contracts(repository: Path, *, check: bool = False) -> list[Path]:
    openapi_text, typescript_text = contract_contents()
    outputs = {
        repository / "contracts" / "jarvis-agent.openapi.json": openapi_text,
        repository
        / "frontend"
        / "src"
        / "features"
        / "jarvis"
        / "api"
        / "generated-contracts.ts": typescript_text,
    }
    changed: list[Path] = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            changed.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    return changed
