// Generated by scripts/workspace/export-jarvis-agent-contracts.py.
// Do not edit manually; update the backend Pydantic contracts and regenerate.

export interface ActionDecision {
  session_id: string;
  payload_hash: string;
  decision: "approve" | "deny";
}

export interface ActionEnvelope {
  result: ActionResponse;
}

export interface ActionResponse {
  action_id: string;
  session_id: string;
  function_call_id: string;
  tool_id: string;
  payload_hash: string;
  preview: { [key: string]: unknown };
  state: "PROPOSED" | "AWAITING_APPROVAL" | "APPROVED" | "DISPATCHING" | "ACCEPTED" | "COMPLETED" | "DENIED" | "CANCELLED" | "EXPIRED" | "FAILED" | "BUSY" | "UNKNOWN";
  status: string;
  expires_at: number | null;
  result: { [key: string]: unknown } | null;
  summary: string;
  error_code: string | null;
  job?: JobResponse | null;
}

export interface AgentEventPollResponse {
  events: Array<AgentEventResponse>;
  next_after: number;
}

export interface AgentEventResponse {
  sequence: number;
  event_id: string;
  event_type: string;
  session_id: string | null;
  action_id: string | null;
  job_id: string | null;
  payload: { [key: string]: unknown };
  created_at: number;
}

export interface CatalogResponse {
  version: string;
  manifest: Array<ManifestEntryResponse>;
  tools: Array<ToolResponse>;
  sources: Array<SourceResponse>;
  providers: Array<ProviderResponse>;
  availability: { [key: string]: [boolean, string | null] };
}

export interface ContextDelete {
  project_key: string;
  codex_thread_id?: string;
}

export interface ContextDeleteResponse {
  deleted: boolean;
}

export interface ContextEnvelope {
  context: ContextResponse;
}

export interface ContextResponse {
  objective: string;
  decisions: Array<{ [key: string]: unknown }>;
  pending: Array<{ [key: string]: unknown }>;
  results: Array<{ [key: string]: unknown }>;
  references: Array<{ [key: string]: unknown }>;
}

export interface EdgeApprovalDecision {
  payload_hash: string;
  decision: "approve" | "deny";
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface JobEnvelope {
  result: JobResponse;
}

export interface JobResponse {
  job_id: string;
  action_id: string;
  state: "ACCEPTED" | "RUNNING" | "COMPLETED" | "FAILED" | "BUSY" | "CANCELLED" | "UNKNOWN";
  result: { [key: string]: unknown } | null;
  summary: string;
  error_code: string | null;
  updated_at: number;
}

export interface ManifestEntryResponse {
  name: string;
  description: string;
  parameters: { [key: string]: unknown };
}

export interface ProposalCreate {
  generation: number;
  function_call_id: string;
  name: string;
  arguments?: { [key: string]: unknown };
  turn_id?: string | null;
}

export interface ProviderResponse {
  id: string;
  status: string;
  connected: boolean;
  operational: boolean;
  capabilities: Array<string>;
  reason?: string | null;
}

export interface ProviderWebhookResponse {
  status: "accepted";
  disposition: string;
  event_id: string;
}

export interface SessionClose {
  generation: number;
}

export interface SessionCloseResponse {
  session_id: string;
  generation: number;
  state: "CLOSED";
}

export interface SessionCreate {
  project_key: string;
  codex_thread_id?: string;
}

export interface SessionResponse {
  session_id: string;
  generation: number;
  state: "ACTIVE" | "CLOSED";
  manifest_version: string;
  manifest: Array<ManifestEntryResponse>;
  catalog: CatalogResponse;
  context: ContextResponse;
}

export interface SourceResponse {
  id: string;
  providers: Array<ProviderResponse>;
  manifest_enabled: boolean;
}

export interface ToolResponse {
  id: string;
  name: string;
  description: string;
  source: string;
  provider: string;
  capability: string;
  effect: "READ" | "MUTATION" | "DELEGATION";
  timeout_seconds: number;
  requires_approval: boolean;
  available: boolean;
  unavailable_reason?: string | null;
  input_schema: { [key: string]: unknown };
}

export interface TurnCreate {
  generation: number;
  turn_id: string;
  transcript: string;
  final: true;
}

export interface TurnResponse {
  turn_id: string;
  status: "committed" | "duplicate";
  transcript_hash: string;
  project_key?: string | null;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: {  };
}
